calendars:
  example.ics:
    MergeCalendars:
    - ModifyCalendar:
      - FetchCalendar: https://calendar.google.com/calendar/ical/en.german%23holiday%40group.v.calendar.google.com/public/basic.ics
      - - KeepComponentsIfNameIn:
          - VEVENT
          - TIMEZONE
        - ModifyComponentsIfNameIs:
          - VEVENT
          - - KeepPropertiesIfNameIn:
              - DTSTAMP
              - UID
              - DTSTART
              - DTEND
              - EXDATE
              - EXRULE
              - RDATE
              - RRULE
              - ATTENDEE
            - InsertProperty: SUMMARY:[Personal]
    - ModifyCalendar:
      - FetchCalendar: https://calendar.google.com/calendar/ical/en.german%23holiday%40group.v.calendar.google.com/public/basic.ics
      - - KeepComponentsIfNameIn:
          - VEVENT
          - VTIMEZONE
        - ModifyComponentsIfNameIs:
          - VEVENT
          - - ReplacePropertiesValueIfNameIs:
              - SUMMARY
              - '[Uni] {{ value }}'
    - ModifyCalendar:
      - FetchCalendar: https://americanhistorycalendar.com/eventscalendar?format=ical&viewid=4
      - - ModifyComponentsIfNameIs:
          - VEVENT
          - - ReplacePropertiesValueIfNameIs:
              - SUMMARY
              - '[fcio] {{ value }}'

